name: CI [develop]

on:
  push:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/test.yaml
      - uses: ./.github/workflows/docker.yaml
        with:
          image-group: fhir-vaccination-pass
          image-name: vaccination-pass-server
          image-tag: latest-develop
